### ISSUE TITLE
two sync with HC

### ISSUE THREAD

**Issue by uzaif313** [tsykoduk/HCRailsDemo#24]
when we delete record from our local schema. is it possible to delete same record from salesforce?
heroku connect provide `isdeleted` field for tracking delete but its not working as i expected. when i am deleteting record i am making `isdeleted` flag as true but its rsync after sometimes

**Comment by tsykoduk** [comment]
You can simply delete the record from PG, and Connect will delete it from SFDC: https://devcenter.heroku.com/articles/writing-data-to-salesforce-with-heroku-connect
